version: '3'

services:
  mongo:
    image: mongo:1.0.0
    build: ./database
    restart: always
    networks:
      - back
    ports:
      - 27017:27017

  api:
    image: api:1.0.0
    build: ../api
    restart: always
    networks:
      - front
      - back
    depends_on:
      - mongo

  web:
    image: web:1.0.0
    build: ../web
    restart: always
    networks:
      - front
    depends_on:
      - api

  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx/conf.d/proxy.conf
      - /dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/hiresmart.app/fullchain.pem:/etc/letsencrypt/live/hiresmart.app/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/hiresmart.app/privkey.pem:/etc/letsencrypt/live/hiresmart.app/privkey.pem
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/proxy.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    networks:
      - front
    ports:
      - 80:80
    depends_on:
      - mongo
      - api
      - web

networks:
  front:
    driver: bridge
  back:
    driver: bridge
